language: go
go: [ 1.11.x ]

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
install:
  - dep ensure
  - gometalinter --install
script: make ci
after_success: bash <(curl -s https://codecov.io/bash)
